# Generated by Django 5.2 on 2025-05-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_attachments_task_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='attachments',
            new_name='files',
        ),
    ]
