# Generated by Django 5.2 on 2025-05-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_attachments_task_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='files',
            new_name='attachments',
        ),
    ]
