# Generated by Django 5.2 on 2025-05-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_task_attachments_remove_task_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedfiles',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
